site_name: PVGeo
site_author: Bane Sullivan
site_description: "Welcome to the documentation for the PVGeo code repository. PVGeo is a code base tailored to the visualization of spatially referenced data in the geosciences on the ParaView software platform. "
repo_url: https://github.com/OpenGeoVis/PVGeo
repo_name: PVGeo on GitHub
site_url: http://pvgeo.org/
edit_uri: ""
copyright: Copyright &copy 2017-2018, <a href="http://banesullivan.com">Bane Sullivan</a>

google_analytics:
  - 'UA-115959679-1'
  - 'auto'

extra:
  disqus: 'pvgeo'
  social: # check https://fontawesome.com/icons?d=gallery for more icons
    - type: 'slack'
      link: 'http://slack.pvgeo.org'
    - type: 'github'
      link: 'https://github.com/OpenGeoVis'
    - type: 'envelope'
      link: 'mailto:info@pvgeo.org'

theme:
    name: material
    feature:
        tabs: true
    palette:
        primary: 'blue-grey'
        accent: 'red'
    custom_dir: custom_theme
    favicon: 'img/globe_small.png'
    logo: 'img/globe_small.png'

extra_css:
    - stylesheets/extra.css


markdown_extensions:
    # Make sure parent directory is in pyhton path when building docs
    - download_button # Adds ability to have full width download buttons

    - smarty
    - toc:
        permalink: true
    - admonition
    - codehilite:
        #linenums: true
        guess_lang: true
    - meta # see this page: https://squidfunk.github.io/mkdocs-material/extensions/metadata/
    - footnotes # see this page: https://squidfunk.github.io/mkdocs-material/extensions/footnotes/
    - pymdownx.b64 # local images
    - pymdownx.superfences # code snippets
    - pymdownx.inlinehilite #example: import the NumPy module by `#!py import numpy`
    - pymdownx.caret # ability to add exponents with caret: a^3
    - pymdownx.details # collapsible widgets
    - pymdownx.tasklist:
        custom_checkbox: true

plugins:
    - search

pages:
- Overview:
    - Home: index.md
    - Why PVGeo?: overview/why-pvgeo.md
    - Getting Started: overview/getting-started.md
    - Features to Come: overview/upcoming.md

# Each of the different Examples:
- Examples:
    - About Examples: examples/about-examples.md
    - Base Classes: examples/base.md
    - General Filters:
        - Voxelize Points: examples/filters-general/voxelize-points.md
        - Many Slices Along Points: examples/filters-general/many-slices-along-points.md
        - Many Slices Along Axis: examples/filters-general/many-slices-along-axis.md
        - Slice Through Time: examples/filters-general/slice-through-time.md
        - Normalize Array: examples/filters-general/normalize-array.md
        - Array Math: examples/filters-general/array-math.md
        - Reshape Table: examples/filters-general/reshape-table.md
        - Combine Tables: examples/filters-general/combine-tables.md
        - Extract Points: examples/filters-general/extract-points.md
        - Points to PolyData: examples/filters-general/points-to-polydata.md
        - Rotate Points: examples/filters-general/rotate-points.md
        - Rotation Tool: examples/filters-general/rotation-tool.md
        - Add Cell Connectivity to Points: examples/filters-general/add-cell-connectivity-to-points.md
        - Points to Tube: examples/filters-general/points-to-tube.md
    - General Readers:
        - Binary Packed Data: examples/readers-general/binary-packed-data.md
        - Madagascar SSRSF: examples/readers-general/madagascar-ssrsf.md
        - Delimited Text: examples/readers-general/delimited-text.md
        - XYZ Files: examples/readers-general/xyz-reader.md
    - UBC Mesh Tools:
        - Read Tensor Meshes: examples/ubc/tensor-grids.md
        - Read OcTree: examples/ubc/octree.md
        - Append Model: examples/ubc/add-model.md
    - GSLIB & SGeMS:
        - SGeMS Grid: examples/gslib/sgems-grid.md
        - GSLIB Table: examples/gslib/gslib.md
    - Model Building:
        - Create Rectilinear Grid: examples/model-building/create-rectilinear-grid.md
        - Create Unifrom Grid: examples/model-building/create-uniform-grid.md
        - Create Earth Source: examples/model-building/create-earth-source.md
    - Grids Tools:
        - Table to Uniform Grid: examples/grids/table-to-uniform-grid.md
        - Flip Grid Axii: examples/grids/reverse-grid-axii.md
        - Translate Origin of Grid: examples/grids/translate-origin-of-grid.md
    - Tunneling:
        - Animate TBM: examples/tunneling/animate-tbm.md

- Docs:
    - Docs: docs-fwd.md

- PV Macros:
    - About pvmacros: pvmacros/about-pvmacros.md
    - Export:
        - Export as VTKjs:  pvmacros/export/exportvtkjs.md
    - Vis:
        - Camera: pvmacros/vis/camera.md

- Resources:
    - Color Maps: cmaps.md
    - Scripts:
        - About Scripts: scripts/about-scripts.md
        - Example Script: scripts/example-script.md
    - Entering Virtual Reality: virtual-reality/entering-virtual-reality.md
    - Editing the Axes: resources/edit-axes.md
    - Editing the Render View: resources/edit-render-view.md
    - Save Camera Views: resources/save-camera-locations.md
    - Understand VTK Data Types: resources/understand-vtk.md

- Development Guide:
    - Contributing: dev-guide/contributing.md
    - Repo Structure: dev-guide/repo-structure.md
    - Build Your Own Plugins: dev-guide/build-your-own-plugins.md
